function varvisc_write_augmentation_report(results_root,cfg,T,summary)
%VARVISC_WRITE_AUGMENTATION_REPORT Concise measured findings and artifact links.
    fid=fopen(fullfile(results_root,'augmentation_report.md'),'w');
    assert(fid>=0,'Cannot create augmentation report.');
    cleanup=onCleanup(@()fclose(fid));
    fprintf(fid,'# Gaussian recycling plus projected Arnoldi\n\n');
    fprintf(fid,['Mesh h=%.3g; dt=%.3g; %d solves per case; MINRES tolerance %.1e; ' ...
        'Gaussian sketch 500 x 2 in the full experiment (this run: %d columns); ' ...
        'two power rounds; tau=%.3g.\n\n'],cfg.params.h0,cfg.params.dt, ...
        cfg.params.Tstep-1,cfg.params.SOLVER_TOL, ...
        cfg.params.DEFLAT_SM_EIG*cfg.params.SKETCH_OVERSAMPLE,cfg.params.DEFLAT_TAU);
    if contains(results_root,'smoke')
        fprintf(fid,'This is a reduced integration check, not the full benchmark evidence.\n\n');
    end
    fprintf(fid,['The Gaussian physical basis is shared and frozen at step 1, then transported ' ...
        'into each current ILDL coordinate system. Fresh W uses projected-RHS-start ' ...
        'Arnoldi on (I-VV^T) Ahat (I-VV^T). The main arm retains V and adds %d ' ...
        'vectors; W is discarded after each solve.\n\n'],cfg.params.AUGMENT_M);
    if isfield(cfg,'case_start_rng')
        fprintf(fid,['Each case starts from the same recorded seed-1 RNG state after mesh ' ...
            'construction. Cases can be run separately and finalized from checkpoints.\n\n']);
    end
    fprintf(fid,'## Measured comparisons\n\n');
    fprintf(fid,'| Case | m | Mean iterations | Max iterations | Iterations saved | Valid steps |\n');
    fprintf(fid,'|---|---:|---:|---:|---:|---:|\n');
    for j=1:height(summary)
        fprintf(fid,'| %s | %d | %.2f | %d | %.1f%% | %d/%d |\n', ...
            summary.case_name{j},summary.m(j),summary.mean_iterations(j), ...
            summary.max_iterations(j),summary.iteration_saving_percent(j), ...
            summary.valid_steps(j),summary.steps(j));
    end
    fprintf(fid,'\nThe comparison focuses on iteration counts, accuracy, spectra and subspace quality.\n\n');
    fprintf(fid,['A valid step has solver flag 0, physical relative residual <=1e-6, and ' ...
        'relative solution error against backslash <=1e-5. All rows, including invalid ' ...
        'ones, remain in the aggregate table. Comparisons with invalid steps describe ' ...
        'behavior at the configured split tolerance, not demonstrated convergence improvement at ' ...
        'equal physical accuracy.\n\n']);
    fprintf(fid,'## Numerical diagnostics\n\n');
    fprintf(fid,'- Maximum ||V^T W||_F: %.3e.\n',max(T.vw_orth));
    fprintf(fid,'- Maximum ||W^T W-I||_F: %.3e.\n',max(T.ww_orth));
    fprintf(fid,'- Maximum relative Arnoldi relation error: %.3e.\n',max(T.arnoldi_relation));
    fprintf(fid,'- Augmentation shortfalls: %d/%d rows.\n',sum(T.augment_rank<T.m),height(T));
    fprintf(fid,'- Physical-residual threshold exceeded: %d/%d rows.\n',sum(T.true_relres>1e-6),height(T));
    fprintf(fid,'- Solution-error threshold exceeded: %d/%d rows.\n',sum(T.err>1e-5),height(T));
    fprintf(fid,['\nSpectra are independent %d-vector projected-Arnoldi estimates at saved ' ...
        'snapshots. Filled markers meet the recorded relative eigenpair-residual ' ...
        'threshold; unfilled markers remain estimates. Forced zeros on the deflated ' ...
        'space are excluded and counted separately. The after-augmentation operator ' ...
        'is the projection onto [V,W]^perp, not the full two-level preconditioned ' ...
        'MINRES operator.\n\n'],cfg.params.AUGMENT_PROBE_DIM);
    fprintf(fid,'## Inspection figures\n\n');
    for c=1:numel(cfg.case_names)
        name=cfg.case_names{c};
        fprintf(fid,'- **%s:** [iterations](%s/augmentation_plots/gaussian_comparison.png), ',name,name);
        fprintf(fid,'[subspaces](%s/augmentation_plots/subspace_diagnostics.png), ',name);
        fprintf(fid,'[accuracy](%s/augmentation_plots/paired_accuracy.png), ',name);
        fprintf(fid,'[spectra](%s/augmentation_plots/projected_spectra.png).\n',name);
    end
    fprintf(fid,'\n[Rotating-bar dimension sweep](bar_rotating_nu_orbiting/augmentation_plots/dimension_sweep.png).\n');
    fprintf(fid,'\nData: [per-step measurements](augmentation_results.csv), [summary](augmentation_summary.csv), [validation](augmentation_validation.csv).\n');
end
