function summary = varvisc_write_dynamic_tau_summary(results_root, all_stats, geometry)
%VARVISC_WRITE_DYNAMIC_TAU_SUMMARY Focused ILDL/deflation evidence table.

    base_key = 'ildl_nofill';
    fixed_key = 'two_level_exact_fixed_tau';
    dynamic_key = 'two_level_exact_dynamic_tau';
    required = {base_key, fixed_key, dynamic_key};

    rows = cell(numel(all_stats), 1);
    for k = 1:numel(all_stats)
        st = all_stats{k};
        assert(all(ismember(required, st.solver_keys)), ...
            'Dynamic-tau summary requires the focused three-solver profile.');
        ib = st.solver_its.(base_key)(:);
        iff = st.solver_its.(fixed_key)(:);
        id = st.solver_its.(dynamic_key)(:);
        tb = st.solver_time.(base_key)(:);
        tf = st.solver_time.(fixed_key)(:);
        td = st.solver_time.(dynamic_key)(:);
        tau = st.solver_info.(dynamic_key).tau(:);
        cutoff = st.solver_info.(dynamic_key).cutoff_abs(:);

        rows{k} = table({geometry}, {st.case_name}, numel(ib), ...
            mean(ib), median(ib), mean(iff), median(iff), ...
            mean(id), median(id), median(ib ./ max(id, 1)), ...
            median(ib ./ max(iff, 1)), median(iff ./ max(id, 1)), ...
            sum(ib), sum(iff), sum(id), ...
            sum(tb), sum(tf), sum(td), min(tau), median(tau), max(tau), ...
            min(cutoff), median(cutoff), max(cutoff), ...
            sum(st.solver_flag.(base_key) ~= 0), ...
            sum(st.solver_flag.(fixed_key) ~= 0), ...
            sum(st.solver_flag.(dynamic_key) ~= 0), ...
            max(st.solver_true_relres.(dynamic_key)), ...
            max(st.solver_err.(dynamic_key)), ...
            'VariableNames', {'geometry', 'case_name', 'systems', ...
            'ildl_mean_its', 'ildl_median_its', ...
            'fixed_tau_mean_its', 'fixed_tau_median_its', ...
            'dynamic_tau_mean_its', 'dynamic_tau_median_its', ...
            'ildl_to_dynamic_median_speedup', ...
            'ildl_to_fixed_median_speedup', ...
            'fixed_to_dynamic_median_speedup', ...
            'ildl_total_its', 'fixed_tau_total_its', ...
            'dynamic_tau_total_its', 'ildl_total_time_s', ...
            'fixed_tau_total_time_s', 'dynamic_tau_total_time_s', ...
            'dynamic_tau_min', 'dynamic_tau_median', 'dynamic_tau_max', ...
            'cutoff_abs_min', 'cutoff_abs_median', 'cutoff_abs_max', ...
            'ildl_failures', 'fixed_tau_failures', 'dynamic_tau_failures', ...
            'dynamic_tau_max_true_relres', 'dynamic_tau_max_solution_error'});
    end
    summary = vertcat(rows{:});
    writetable(summary, fullfile(results_root, 'dynamic_tau_summary.csv'));

    fid = fopen(fullfile(results_root, 'dynamic_tau_summary.txt'), 'w');
    if fid < 0
        error('varvisc_write_dynamic_tau_summary:open', ...
            'Could not create dynamic_tau_summary.txt.');
    end
    cleanup = onCleanup(@() fclose(fid));
    for k = 1:height(summary)
        fprintf(fid, ...
            ['%s: ILDL mean %.2f, fixed-tau mean %.2f, dynamic-tau mean %.2f; ' ...
             'median ILDL/fixed %.3fx, ILDL/dynamic %.3fx; tau %.6g..%.6g; ' ...
             'end-to-end time %.3fs (ILDL) vs %.3fs (dynamic).\n'], ...
            summary.case_name{k}, summary.ildl_mean_its(k), ...
            summary.fixed_tau_mean_its(k), summary.dynamic_tau_mean_its(k), ...
            summary.ildl_to_fixed_median_speedup(k), ...
            summary.ildl_to_dynamic_median_speedup(k), ...
            summary.dynamic_tau_min(k), summary.dynamic_tau_max(k), ...
            summary.ildl_total_time_s(k), summary.dynamic_tau_total_time_s(k));
    end
end
