function [V, info] = gaussian_subspace_basis( ...
        sketchApply, n, k, q, oversampling)
%GAUSSIAN_SUBSPACE_BASIS  Return the full oversampled Gaussian sketch basis.
%   The sampled subspace is orthogonalized once after q operator products.
%   No Rayleigh--Ritz projection, rotation, selection, or truncation is used.

    if ~isa(sketchApply,'function_handle')
        error('gaussian_subspace_basis:badHandle', ...
              'sketchApply must be a function handle.');
    end
    validateattributes(n,{'numeric'},{'scalar','integer','positive'});
    validateattributes(k,{'numeric'},{'scalar','integer','positive','<=',n});
    validateattributes(q,{'numeric'},{'scalar','integer','nonnegative'});
    validateattributes(oversampling,{'numeric'}, ...
        {'scalar','real','finite','>=',1});

    sketchWidth = min(n,ceil(oversampling*k));
    sample = src.precond.subspace_iter_plain( ...
        sketchApply,randn(n,sketchWidth),q);
    V = orth(real(sample));
    if size(V,2) ~= sketchWidth
        error('gaussian_subspace_basis:rankLoss', ...
              'Final sketch rank %d differs from requested width %d.', ...
              size(V,2),sketchWidth);
    end

    info = struct('nominalRank',k, ...
                  'oversampling',oversampling, ...
                  'sketchWidth',sketchWidth, ...
                  'realizedSketchRank',size(V,2), ...
                  'orthogonalityResidual', ...
                  norm(V'*V-eye(sketchWidth),'fro'));
end
