function test_varvisc_schur_two_stage_augmentation()
%TEST_VARVISC_SCHUR_TWO_STAGE_AUGMENTATION Shared augmented space and integration.
    here=fileparts(mfilename('fullpath')); addpath(fileparts(here));
    add_varvisc_schur_paths(); rng(41);
    n=70; [Q,~]=qr(randn(n)); S=Q*diag(logspace(-2,1,n))*Q'; S=(S+S')/2;
    small=orth(Q(:,1:4)+.04*randn(n,4));
    large=orth(Q(:,end-5:end)+.04*randn(n,6));
    V=orth([large,small]); b=randn(n,1); x0=randn(n,1); r=b-S*x0;
    tau1=3; tau2=.4; m=12; before=rng;
    [P,F,info,d]=varvisc_schur_two_stage_augmentation(@(x)S*x,V,r,m,tau1,tau2,true);
    assert(isequal(before,rng) && isequal(d.V,V));
    assert(info.base_rank==10 && info.aug_rank==m && info.total_rank==10+m);
    assert(norm(small'*d.W,'fro')<1e-12 && norm(large'*d.W,'fro')<1e-12);
    Pi=eye(n)-V*V';
    [expected,~]=varvisc_build_projected_arnoldi(@(x)Pi*S*Pi*x,[],Pi*r,m);
    assert(norm(d.W-expected*(expected'*d.W),'fro')<1e-10);
    assert(norm(d.W(:,1)-Pi*r/norm(Pi*r))<1e-12,'Warm-start residual was not used.');
    Z=d.Z; E=Z'*S*Z; E=(E+E')/2; [U,D]=eig(E);
    H1=eye(n)-Z*Z'+sqrt(tau1)*Z*U*diag(1./sqrt(diag(D)))*U'*Z';
    S1=H1*S*H1; E2=Z'*S1*Z;
    P2=eye(n)-Z*Z'+tau2*Z*(E2\Z');
    Poracle=H1*P2*H1;
    assert(norm(d.E1-E,'fro')/norm(E,'fro')<1e-12);
    assert(norm(d.E2-E2,'fro')/norm(E2,'fro')<1e-10);
    assert(norm(P(eye(n))-Poracle,'fro')/norm(Poracle,'fro')<1e-10);
    assert(norm(d.P1half(eye(n))-H1,'fro')/norm(H1,'fro')<1e-12);
    PP=P(eye(n)); assert(norm(PP-PP','fro')/norm(PP,'fro')<1e-12);
    R=chol((PP+PP')/2,'lower'); FF=F(eye(n));
    assert(norm(FF-FF','fro')/norm(FF,'fro')<1e-12);
    assert(norm(sort(eig(FF))-sort(eig(R'*S*R)))/norm(eig(FF))<1e-10);
    [x,flag]=pcg(@(x)S*x,b,1e-11,1000,P,[],x0);
    assert(flag==0 && norm(x-S\b)/norm(S\b)<1e-9);
    assert(max([info.vw_orth,info.ww_orth,info.arnoldi_relerr])<1e-10);
    [P0,~,i0]=varvisc_schur_two_stage_augmentation(@(x)S*x,V,r,0,tau1,tau2);
    H0=src.precond.deflation_Psqrt_apply(V,@(x)S*x,tau1,'handle');
    S0=@(x)H0(S*H0(x)); C0=src.precond.deflation_P_apply(V,S0,tau2,'handle',0);
    assert(isequal(P0(b),H0(C0(H0(b)))) && i0.aug_rank==0);
    [~,~,iz]=varvisc_schur_two_stage_augmentation(@(x)S*x,V,zeros(n,1),m,tau1,tau2);
    assert(iz.aug_rank==0 && iz.arnoldi_status==1);
    [~,~,iz]=varvisc_schur_two_stage_augmentation(@(x)S*x,V,V(:,1),m,tau1,tau2);
    assert(iz.aug_rank==0 && iz.arnoldi_status==1);
    [~,~,ii]=varvisc_schur_two_stage_augmentation(@(x)x,V,b,m,tau1,tau2);
    assert(ii.aug_rank==1 && ii.arnoldi_status==2);
    [~,~,ic]=varvisc_schur_two_stage_augmentation(@(x)S*x,Q(:,1:n-3),b,m,tau1,tau2);
    assert(ic.aug_rank<=3 && ic.arnoldi_columns<=3);

    p=make_varvisc_schur_params(); p.h0=.2; p.max_steps=4;
    p.sm_eig=4; p.lg_eig=4; p.AUGMENT_M=5;
    p.SMALL_BASIS_REFRESH=2; p.DEFLAT_SHARED_LARGE_REFRESH=3;
    p.standalone_variants=p.standalone_variants([3,end]);
    cfg=varvisc_schur_make_cfg('bar_rotating_nu_orbiting',p,[]);
    base='deflate_sequential_shared_subspace'; aug='deflate_sequential_shared_subspace_augmented';
    rng(9); A=solve_varvisc_schur_sequence(cfg,p,''); after=rng;
    assert(isequal(A.basis_built_step.(aug),[1 3 4]));
    assert(isequal(A.large_basis_built_step.(aug),[1 4]));
    assert(isequal(A.deflation_tau.augmented_stage1,A.deflation_tau.sequential_stage1));
    assert(isequal(A.deflation_tau.augmented_stage2,A.deflation_tau.sequential_stage2));
    d=A.augmentation.(aug);
    assert(all(d.base_rank==12) && all(d.aug_rank==5) && all(d.total_rank==17));
    assert(isequal(d.residual_columns,[0;1;1;1]) && all(d.arnoldi_columns==5));
    assert(isequal(A.dense_materialized_step,1) && isempty(A.kkt_materialized_step));
    assert(all(A.solver_flag.(aug)==0) && max(A.solver_true_relres.(aug))<=p.SOLVER_TOL);
    assert(max(A.solver_err.(aug))<1e-5);
    % No extra random draws or basis changes when adding the augmented arm.
    pb=p; pb.standalone_variants=pb.standalone_variants(1);
    rng(9); B=solve_varvisc_schur_sequence(cfg,pb,'');
    assert(isequal(after,rng) && isequal(A.solver_its.(base),B.solver_its.(base)));
    % The augmented arm can run alone and still builds the same shared caches.
    pa=p; pa.standalone_variants=pa.standalone_variants(2);
    rng(9); Alone=solve_varvisc_schur_sequence(cfg,pa,'');
    assert(isequal(A.solver_its.(aug),Alone.solver_its.(aug)));
    assert(isequal(Alone.basis_built_step.(aug),[1 3 4]));
    p0=p; p0.AUGMENT_M=0;
    rng(9); Zero=solve_varvisc_schur_sequence(cfg,p0,'');
    assert(isequal(Zero.solver_its.(aug),Zero.solver_its.(base)));
    assert(isequal(Zero.solver_err.(aug),Zero.solver_err.(base)));
    % Optional spectrum must use the augmented two-stage operator.
    ps=p; ps.max_steps=1; ps.PLOT_EXTREME_EIGENVALUES=true;
    ps.EXACT_REFERENCE_DIAGNOSTICS=true;
    rng(9); Spectral=solve_varvisc_schur_sequence(cfg,ps,'');
    assert(Spectral.system_lambda_min.(aug)>0 && Spectral.system_spectrum_flag.(aug)==0);
    assert(Spectral.vel_recovery_err(1)<1e-8);
    % CSV, matched report, saved-config and legacy replot paths.
    folder=tempname; mkdir(folder); cleanup=onCleanup(@()rmdir(folder,'s'));
    write_varvisc_schur_all_results(folder,{A}); write_varvisc_schur_speedup(folder,{A});
    T=readtable(fullfile(folder,'all_results.csv'));
    assert(isequal(T.([aug '_its']),A.solver_its.(aug)));
    assert(all(T.([aug '_aug_rank'])==5));
    assert(isequal(T.chol_flag,A.solver_flag.chol));
    assert(isequaln(T.factor_chol_flag,A.chol_flag));
    assert(isfile(fullfile(folder,'two_stage_augmentation_report.md')));
    cfg_dump=struct('solver_keys',{A.solver_keys},'solver_labels',{A.solver_labels});
    save(fullfile(folder,'run_config.mat'),'cfg_dump');
    replot_varvisc_schur(folder);
    assert(isfile(fullfile(folder,A.case_name,'two_stage_augmentation_comparison.png')));
    assert(~isfile(fullfile(folder,A.case_name,'reference_solver_iterations.png')));
    delete(fullfile(folder,'run_config.mat'));
    replot_varvisc_schur(folder);
    assert(~isfile(fullfile(folder,A.case_name,'reference_solver_iterations.png')));
    fprintf('PASS: two-stage shared augmentation, warm starts, refresh, spectra, CSV and replot.\n');
end
