% TEST_VARVISC_SCHUR_ADAPTIVE_TUNING  Smoke-test the two-stage tuner.
clear; clc;
thisDir = fileparts(mfilename('fullpath')); addpath(fileparts(thisDir));
add_varvisc_schur_paths();

outputDir = tempname; mkdir(outputDir);
cleanupOutput = onCleanup(@() rmdir(outputDir,'s'));
options = struct('smoke',true,'outputDir',outputDir,'seed',3, ...
    'tauMultipliers',1,'qList',0,'finalistCount',1);
result = run_varvisc_schur_adaptive_tuning(options);

assert(height(result.coarseSummary) == 3, ...
       'Smoke grid must contain dynamic, current, and fixed-dynamic tau.');
assert(height(result.fineSummary) == 1, ...
       'Smoke grid promoted an unexpected number of finalists.');
assert(result.fineSummary.small_dim == 2 && ...
       result.fineSummary.large_dim == 4, ...
       'Smoke tuning changed its fixed basis dimensions.');
assert(isinf(result.fineSummary.refresh_interval), ...
       'Adaptive tuning must keep the refresh interval frozen at Inf.');
assert(result.fineSummary.all_converged && ...
       result.fineSummary.valid_spectrum, ...
       'The smoke finalist did not produce a valid solve and spectrum.');
assert(isfield(result.recommendation,'lift_large_q') && ...
       isfield(result.recommendation,'worst_kappa'), ...
       'The recommendation is incomplete.');

required = {'coarse_summary.csv','coarse_timesteps.csv', ...
    'fine_summary.csv','fine_timesteps.csv','comparison_summary.csv', ...
    'comparison_timesteps.csv','recommended_config.json', ...
    'adaptive_tuning.mat'};
for index = 1:numel(required)
    filename = fullfile(outputDir,required{index});
    assert(exist(filename,'file') == 2 && dir(filename).bytes > 0, ...
           'Missing tuning artifact %s.',required{index});
end

fprintf('test_varvisc_schur_adaptive_tuning: ALL ASSERTIONS PASSED\n');
