% TEST_VARVISC_SCHUR_REGISTRY  Shared small/large cache smoke test.
clear; clc;
thisDir = fileparts(mfilename('fullpath')); addpath(fileparts(thisDir));
add_varvisc_schur_paths(); rng(1);
p = make_varvisc_schur_params();
assert(p.sm_eig == 20 && p.lg_eig == 100, ...
       'Default target tail dimensions are not 20 and 100.');
assert(strcmp(p.small_basis_source,'lanczos'), ...
       'The default shared-small source must be Lanczos.');
assert(~p.EXACT_REFERENCE_DIAGNOSTICS && p.REFERENCE_TOL < p.SOLVER_TOL, ...
       'The default reference must be tighter and matrix-free.');
assert(p.sketch_oversampling == 2, ...
       'The default Gaussian sketch oversampling must be two.');
refreshFields = {'SMALL_BASIS_REFRESH', ...
    'DEFLAT_SHARED_LARGE_REFRESH', ...
    'DEFLAT_ADAPTIVE_LIFT_LARGE_REFRESH'};
for fieldIndex = 1:numel(refreshFields)
    assert(isinf(p.(refreshFields{fieldIndex})), ...
           'Default refresh interval %s must be Inf.',refreshFields{fieldIndex});
end

p.h0 = .1; p.max_steps = 4; p.sm_eig = 4; p.lg_eig = 4;
p.SMALL_BASIS_REFRESH = 2;
p.DEFLAT_SHARED_LARGE_REFRESH = 3;
p.DEFLAT_ADAPTIVE_LIFT_LARGE_REFRESH = Inf;
cfg = varvisc_schur_make_cfg('bar_rotating_nu_orbiting',p,[]);
A = solve_varvisc_schur_sequence(cfg,p,'');
expected = {'pcg_unprec','chol','deflate_shared_small', ...
    'deflate_gaussian_large','deflate_sequential_shared_subspace', ...
    'deflate_concatenated_once','deflate_adaptive_small_lift_large'};
assert(isequal(A.solver_keys(:)',expected),'Unexpected registry ordering.');
for keyIndex = 1:numel(expected)
    key = expected{keyIndex};
    assert(all(A.solver_flag.(key) == 0),'%s failed to converge.',key);
    assert(max(A.solver_err.(key)) < 1e-5, ...
           '%s solution error is too large.',key);
end

assert(isequal(A.chol_built_step,1),'Frozen Cholesky was not built once.');
assert(isequal(A.dense_materialized_step,1), ...
       'Operator-first benchmark materialized S after the frozen factor build.');
assert(isempty(A.kkt_materialized_step), ...
       'Operator-first benchmark unexpectedly materialized a KKT matrix.');
assert(all(A.reference_flag == 0) && max(A.schur_ref_relres) < 1e-9, ...
       'Matrix-free reference solve did not reach its requested accuracy.');
assert(isequal(A.small_basis_built_step,[1 3]), ...
       'The central small basis did not honor its refresh interval.');
assert(isequal(A.basis_built_step.deflate_shared_small,[1 3]), ...
       'The small-only arm did not consume central small refreshes.');
assert(isequal(A.shared_large_basis_built_step,[1 4]), ...
       'The central large basis did not honor its refresh interval.');
assert(isequal(A.large_basis_built_step.deflate_gaussian_large,[1 4]), ...
       'The standalone arm did not consume shared large refreshes.');
assert(isequal( ...
    A.large_basis_built_step.deflate_sequential_shared_subspace,[1 4]), ...
       'Sequential arm did not consume shared large refreshes.');
assert(isequal(A.large_basis_built_step.deflate_concatenated_once,[1 4]), ...
       'Concatenated arm did not consume shared large refreshes.');
assert(isequal(A.basis_built_step.deflate_sequential_shared_subspace,[1 3 4]), ...
       'Sequential basis did not track small and shared-large refreshes.');
assert(isequal(A.basis_built_step.deflate_concatenated_once,[1 3 4]), ...
       'Concatenated basis did not track small and shared-large refreshes.');
assert(isequal(A.large_basis_built_step.deflate_adaptive_small_lift_large,[1 3]), ...
       'A small refresh did not force the transformed large sketch to rebuild.');

assert(A.deflat_dim.deflate_shared_small == p.sm_eig, ...
       'Shared-small target rank was not retained.');
gaussianLargeWidth = ceil(p.sketch_oversampling*p.lg_eig);
adaptiveLargeWidth = ceil( ...
    p.sketch_oversampling*(p.sm_eig+p.lg_eig));
assert(A.deflat_dim.deflate_gaussian_large == gaussianLargeWidth, ...
       'Large Gaussian basis did not retain the full oversampled width.');
assert(A.deflat_dim.deflate_sequential_shared_subspace == ...
       p.sm_eig+gaussianLargeWidth, ...
       'Sequential combined target rank was not retained.');
assert(A.deflat_dim.deflate_concatenated_once == ...
       p.sm_eig+gaussianLargeWidth, ...
       'One-shot combined target rank was not retained.');
assert(A.deflat_dim.deflate_adaptive_small_lift_large == ...
       p.sm_eig+adaptiveLargeWidth, ...
       'Lift-plus-large rank accounting is incorrect.');
assert(all(A.large_basis_dim_history.deflate_gaussian_large == ...
       gaussianLargeWidth), ...
       'The large target dimension differs across time.');
assert(all(A.large_basis_dim_history.deflate_sequential_shared_subspace == ...
       gaussianLargeWidth), ...
       'Sequential arm does not use the common large target dimension.');
assert(all(A.large_basis_dim_history.deflate_concatenated_once == ...
       gaussianLargeWidth), ...
       'Concatenated arm does not use the common large target dimension.');
assert(all(A.large_basis_dim_history.deflate_adaptive_small_lift_large == ...
       adaptiveLargeWidth), ...
       'Post-lift arm does not sketch the combined small/large rank.');
assert(A.deflat_tail_dim.shared_large == gaussianLargeWidth, ...
       'Shared large-tail rank accounting is incorrect.');

scale = max(A.lambda_max);
assert(abs(A.deflation_tau.gaussian_large(1)-A.lambda_hi_target(1)) < ...
       1e-12*scale,'Large-only tau is incorrect at the initial build.');
assert(all(A.deflation_tau.gaussian_large(2:3) == ...
       A.deflation_tau.gaussian_large(1)), ...
       'Large-only tau changed without a shared-large refresh.');
assert(abs(A.deflation_tau.gaussian_large(4)-A.lambda_hi_target(4)) < ...
       1e-12*scale,'Large-only tau did not follow the shared refresh.');
assert(abs(A.deflation_tau.sequential_stage1(1)-A.lambda_hi_target(1)) < ...
       1e-12*scale,'Sequential stage-one tau is incorrect.');
assert(A.deflation_tau.sequential_stage1(2) == ...
       A.deflation_tau.sequential_stage1(1), ...
       'Sequential tau changed without either constituent refreshing.');
assert(abs(A.deflation_tau.sequential_stage2(3)-A.tau_star_target(3)) < ...
       1e-12*scale,'Sequential geometric tau was not refreshed correctly.');
assert(abs(A.deflation_tau.sequential_stage2(4)-A.tau_star_target(4)) < ...
       1e-12*scale,'Sequential tau did not follow the shared-large refresh.');
assert(abs(A.deflation_tau.concatenated_once(3)-A.tau_star_target(3)) < ...
       1e-12*scale,'One-shot geometric tau is incorrect.');
assert(abs(A.deflation_tau.concatenated_once(4)-A.tau_star_target(4)) < ...
       1e-12*scale,'One-shot tau did not follow the shared-large refresh.');
assert(abs(A.deflation_tau.adaptive_large(3)-A.tau_star_target(3)) < ...
       1e-12*scale,'Post-lift large tau is incorrect.');
for refreshIndex = 1:numel(A.small_basis_info)
    info = A.small_basis_info{refreshIndex};
    if ~info.usedFixedLiftTau
        assert(abs(info.liftedLambdaHat-info.lambdaMax) < 1e-10*info.lambdaMax, ...
               'Dynamic lift tau does not map lambdaHat to lambdaMax.');
    end
end

pinverse = p;
pinverse.max_steps = 1;
pinverse.small_basis_source = 'inverse_gaussian';
pinverse.standalone_variants = struct( ...
    'name','deflate_shared_small','design','shared_small');
Ainverse = solve_varvisc_schur_sequence(cfg,pinverse,'');
assert(strcmp(Ainverse.small_basis_source,'inverse_gaussian'), ...
       'The central inverse-Gaussian small source was not selected.');
inverseSmallWidth = ceil(pinverse.sketch_oversampling*pinverse.sm_eig);
assert(Ainverse.deflat_dim.deflate_shared_small == inverseSmallWidth, ...
       'The inverse-Gaussian source did not retain its oversampled width.');

pfixed = p;
pfixed.max_steps = 1;
pfixed.lift_tau = 1e-10;
pfixed.standalone_variants = struct( ...
    'name','deflate_adaptive_small_lift_large', ...
    'design','adaptive_small_lift_large');
Afixed = solve_varvisc_schur_sequence(cfg,pfixed,'');
assert(Afixed.lift_tau(1) == pfixed.lift_tau, ...
       'The fixed lift_tau override was not used.');
assert(Afixed.small_basis_info{1}.usedFixedLiftTau, ...
       'The fixed lift_tau selection was not recorded.');

pcompare = p;
pcompare.max_steps = 2;
pcompare.SMALL_BASIS_REFRESH = Inf;
pcompare.DEFLAT_SHARED_LARGE_REFRESH = Inf;
pcompare.standalone_variants = struct( ...
    'name','deflate_gaussian_large','design','gaussian_large');
rng(19); AlargeOnly = solve_varvisc_schur_sequence(cfg,pcompare,'');
pcompare.standalone_variants = p.standalone_variants;
rng(19); Aall = solve_varvisc_schur_sequence(cfg,pcompare,'');
assert(isequal(AlargeOnly.solver_its.deflate_gaussian_large, ...
              Aall.solver_its.deflate_gaussian_large), ...
       'Enabling other arms changed the shared large-only iteration counts.');
assert(max(abs(AlargeOnly.solver_err.deflate_gaussian_large- ...
                   Aall.solver_err.deflate_gaussian_large)) < 1e-14, ...
       'Enabling other arms changed the shared large-only solutions.');

plegacy = rmfield(p,'DEFLAT_SHARED_LARGE_REFRESH');
plegacy.max_steps = 1;
plegacy.DEFLAT_GAUSSIAN_LARGE_REFRESH = 2;
plegacy.DEFLAT_SEQUENTIAL_SHARED_LARGE_REFRESH = 2;
plegacy.DEFLAT_CONCATENATED_ONCE_LARGE_REFRESH = 2;
Alegacy = solve_varvisc_schur_sequence(cfg,plegacy,'');
assert(isequal(Alegacy.shared_large_basis_built_step,1), ...
       'Equal legacy refresh aliases were not accepted.');

pconflict = rmfield(p,'DEFLAT_SHARED_LARGE_REFRESH');
pconflict.DEFLAT_GAUSSIAN_LARGE_REFRESH = 1;
pconflict.DEFLAT_SEQUENTIAL_SHARED_LARGE_REFRESH = 2;
try
    solve_varvisc_schur_sequence(cfg,pconflict,'');
    error('test_varvisc_schur_registry:missingConflictError', ...
          'Conflicting legacy refresh intervals were accepted.');
catch ME
    assert(strcmp(ME.identifier, ...
           'solve_varvisc_schur_sequence:conflictingLargeRefresh'), ...
           'Unexpected legacy conflict error: %s',ME.message);
end

pmixed = p;
pmixed.DEFLAT_SHARED_LARGE_REFRESH = 3;
pmixed.DEFLAT_GAUSSIAN_LARGE_REFRESH = 2;
try
    solve_varvisc_schur_sequence(cfg,pmixed,'');
    error('test_varvisc_schur_registry:missingMixedConflictError', ...
          'Conflicting shared and legacy refresh intervals were accepted.');
catch ME
    assert(strcmp(ME.identifier, ...
           'solve_varvisc_schur_sequence:conflictingLargeRefresh'), ...
           'Unexpected mixed refresh conflict error: %s',ME.message);
end

pbad = p; pbad.DEFLAT_SHARED_LARGE_REFRESH = 0;
try
    solve_varvisc_schur_sequence(cfg,pbad,'');
    error('test_varvisc_schur_registry:missingRefreshError', ...
          'Invalid refresh interval was accepted.');
catch ME
    assert(strcmp(ME.identifier,'solve_varvisc_schur_sequence:badDeflatRefresh'), ...
           'Unexpected error for invalid refresh interval: %s',ME.message);
end
assert(all(isnan(A.vel_recovery_err)), ...
       'Exact-only recovery diagnostics should be absent by default.');
fprintf('test_varvisc_schur_registry: ALL ASSERTIONS PASSED\n');
