% TEST_VARVISC_SCHUR_PROJECTOR  Sketch basis and direct-S deflation projector.
clear; clc;
thisDir = fileparts(mfilename('fullpath')); addpath(fileparts(thisDir));
add_varvisc_schur_paths(); import src.precond.*; rng(7);
p = make_varvisc_schur_params(); p.h0=0.1; k=20;
cfg=varvisc_schur_make_cfg('bar_rotating_nu_orbiting',p,[]);
ctx=varvisc_schur_context_init(cfg,p);
st=varvisc_schur_step_operator(ctx,p.dt,zeros(ctx.nU,1)); S=st.S; n=size(S,1);
[U,D]=eig(S,'vector'); [lam,ord]=sort(real(D)); U=real(U(:,ord)); Ve=U(:,1:k);
R=chol(S,'lower'); Sinv=@(X) R'\(R\X);
V=varvisc_schur_build_sketch_V(Sinv,n,k,p.q);
assert(norm(V'*V-eye(size(V,2)),'fro')<1e-10,'Sketch basis not orthonormal.');
nv=size(V,2); assert(nv>=1 && nv<=k,'Unexpected realized sketch width.');
[Pg,Eg,decEg]=deflation_P_apply(V,S,lam(end),'matrix',0);
assert(isequal(size(Eg),[nv,nv]),'Coarse matrix dropped post-orth columns.');
assert(size(decEg.Z,2)==nv,'Absorbed basis dropped post-orth columns.');
assert(isequal(size(Pg),[n,n]),'Gaussian deflation matrix has the wrong size.');
[~,f]=chol(Eg); assert(f==0,'Coarse matrix not SPD.');
tau=lam(end); P=deflation_P_apply(Ve,S,tau,'matrix',0);
assert(norm(P-P','fro')<1e-10*norm(P,'fro'),'P is nonsymmetric.');
[~,f]=chol((P+P')/2); assert(f==0,'P is not SPD.');
got=sort(real(eig(P*S))); expected=sort([repmat(tau,k,1);lam(k+1:end)]);
assert(max(abs(got-expected))<1e-8*tau,'Captured modes were not relocated to tau.');
fprintf('test_varvisc_schur_projector: ALL ASSERTIONS PASSED\n');
