% TEST_VARVISC_SCHUR_REGISTRY  Shared-small and independent-large smoke test.
clear; clc;
thisDir = fileparts(mfilename('fullpath')); addpath(fileparts(thisDir));
add_varvisc_schur_paths(); rng(1);
p = make_varvisc_schur_params();
assert(p.sm_eig == 20 && p.lg_eig == 50, ...
       'Default target tail dimensions are not 20 and 50.');
assert(strcmp(p.small_basis_source,'lanczos'), ...
       'The default shared-small source must be Lanczos.');
assert(p.sketch_oversampling == 2, ...
       'The default Gaussian sketch oversampling must be two.');
refreshFields = {'SMALL_BASIS_REFRESH', ...
    'DEFLAT_GAUSSIAN_LARGE_REFRESH', ...
    'DEFLAT_SEQUENTIAL_SHARED_LARGE_REFRESH', ...
    'DEFLAT_CONCATENATED_ONCE_LARGE_REFRESH', ...
    'DEFLAT_ADAPTIVE_LIFT_LARGE_REFRESH'};
for fieldIndex = 1:numel(refreshFields)
    assert(isinf(p.(refreshFields{fieldIndex})), ...
           'Default refresh interval %s must be Inf.',refreshFields{fieldIndex});
end

p.h0 = .1; p.max_steps = 3; p.sm_eig = 4; p.lg_eig = 4;
p.SMALL_BASIS_REFRESH = 2;
p.DEFLAT_GAUSSIAN_LARGE_REFRESH = 1;
p.DEFLAT_SEQUENTIAL_SHARED_LARGE_REFRESH = Inf;
p.DEFLAT_CONCATENATED_ONCE_LARGE_REFRESH = 2;
p.DEFLAT_ADAPTIVE_LIFT_LARGE_REFRESH = Inf;
cfg = varvisc_schur_make_cfg('bar_rotating_nu_orbiting',p,[]);
A = solve_varvisc_schur_sequence(cfg,p,'');
expected = {'pcg_unprec','chol','deflate_shared_small', ...
    'deflate_gaussian_large','deflate_sequential_shared_subspace', ...
    'deflate_concatenated_once','deflate_adaptive_small_lift_large'};
assert(isequal(A.solver_keys(:)',expected),'Unexpected registry ordering.');
for keyIndex = 1:numel(expected)
    key = expected{keyIndex};
    assert(all(A.solver_flag.(key) == 0),'%s failed to converge.',key);
    assert(max(A.solver_err.(key)) < 1e-5, ...
           '%s solution error is too large.',key);
end

assert(isequal(A.chol_built_step,1),'Frozen Cholesky was not built once.');
assert(isequal(A.dense_materialized_step,1), ...
       'Operator-first benchmark materialized S after the frozen factor build.');
assert(isequal(A.small_basis_built_step,[1 3]), ...
       'The central small basis did not honor its refresh interval.');
assert(isequal(A.basis_built_step.deflate_shared_small,[1 3]), ...
       'The small-only arm did not consume central small refreshes.');
assert(isequal(A.large_basis_built_step.deflate_gaussian_large,[1 2 3]), ...
       'The standalone large arm did not honor refresh interval one.');
assert(isequal( ...
    A.large_basis_built_step.deflate_sequential_shared_subspace,1), ...
    'Sequential large sketch should stay frozen.');
assert(isequal(A.basis_built_step.deflate_sequential_shared_subspace,[1 3]), ...
       'Sequential combined basis was not rebuilt after the small refresh.');
assert(isequal(A.large_basis_built_step.deflate_concatenated_once,[1 3]), ...
       'Concatenated large sketch did not honor refresh interval two.');
assert(isequal(A.large_basis_built_step.deflate_adaptive_small_lift_large,[1 3]), ...
       'A small refresh did not force the transformed large sketch to rebuild.');

assert(A.deflat_dim.deflate_shared_small == p.sm_eig, ...
       'Shared-small target rank was not retained.');
gaussianLargeWidth = ceil(p.sketch_oversampling*p.lg_eig);
assert(A.deflat_dim.deflate_gaussian_large == gaussianLargeWidth, ...
       'Large Gaussian basis did not retain the full oversampled width.');
assert(A.deflat_dim.deflate_sequential_shared_subspace == ...
       p.sm_eig+gaussianLargeWidth, ...
       'Sequential combined target rank was not retained.');
assert(A.deflat_dim.deflate_concatenated_once == ...
       p.sm_eig+gaussianLargeWidth, ...
       'One-shot combined target rank was not retained.');
assert(A.deflat_dim.deflate_adaptive_small_lift_large == ...
       p.sm_eig+gaussianLargeWidth, ...
       'Lift-plus-large rank accounting is not fair.');
assert(all(A.large_basis_dim_history.deflate_gaussian_large == ...
       gaussianLargeWidth), ...
       'The large target dimension differs across time.');
assert(all(A.large_basis_dim_history.deflate_sequential_shared_subspace == ...
       gaussianLargeWidth), ...
       'Sequential arm does not use the common large target dimension.');
assert(all(A.large_basis_dim_history.deflate_concatenated_once == ...
       gaussianLargeWidth), ...
       'Concatenated arm does not use the common large target dimension.');
assert(all(A.large_basis_dim_history.deflate_adaptive_small_lift_large == ...
       gaussianLargeWidth), ...
       'Post-lift arm does not use the common large target dimension.');

scale = max(A.lambda_max);
assert(max(abs(A.deflation_tau.gaussian_large-A.lambda_hi_target)) < 1e-12*scale, ...
       'Large-only tau does not use the target-rank upper cutoff.');
assert(abs(A.deflation_tau.sequential_stage1(1)-A.lambda_hi_target(1)) < ...
       1e-12*scale,'Sequential stage-one tau is incorrect.');
assert(A.deflation_tau.sequential_stage1(2) == ...
       A.deflation_tau.sequential_stage1(1), ...
       'Sequential tau changed without either constituent refreshing.');
assert(abs(A.deflation_tau.sequential_stage2(3)-A.tau_star_target(3)) < ...
       1e-12*scale,'Sequential geometric tau was not refreshed correctly.');
assert(abs(A.deflation_tau.concatenated_once(3)-A.tau_star_target(3)) < ...
       1e-12*scale,'One-shot geometric tau is incorrect.');
assert(abs(A.deflation_tau.adaptive_large(3)-A.tau_star_target(3)) < ...
       1e-12*scale,'Post-lift large tau is incorrect.');
for refreshIndex = 1:numel(A.small_basis_info)
    info = A.small_basis_info{refreshIndex};
    if ~info.usedFixedLiftTau
        assert(abs(info.liftedLambdaHat-info.lambdaMax) < 1e-10*info.lambdaMax, ...
               'Dynamic lift tau does not map lambdaHat to lambdaMax.');
    end
end

pinverse = p;
pinverse.max_steps = 1;
pinverse.small_basis_source = 'inverse_gaussian';
pinverse.standalone_variants = struct( ...
    'name','deflate_shared_small','design','shared_small');
Ainverse = solve_varvisc_schur_sequence(cfg,pinverse,'');
assert(strcmp(Ainverse.small_basis_source,'inverse_gaussian'), ...
       'The central inverse-Gaussian small source was not selected.');
inverseSmallWidth = ceil(pinverse.sketch_oversampling*pinverse.sm_eig);
assert(Ainverse.deflat_dim.deflate_shared_small == inverseSmallWidth, ...
       'The inverse-Gaussian source did not retain its oversampled width.');

pfixed = p;
pfixed.max_steps = 1;
pfixed.lift_tau = 1e-10;
pfixed.standalone_variants = struct( ...
    'name','deflate_adaptive_small_lift_large', ...
    'design','adaptive_small_lift_large');
Afixed = solve_varvisc_schur_sequence(cfg,pfixed,'');
assert(Afixed.lift_tau(1) == pfixed.lift_tau, ...
       'The fixed lift_tau override was not used.');
assert(Afixed.small_basis_info{1}.usedFixedLiftTau, ...
       'The fixed lift_tau selection was not recorded.');

pbad = p; pbad.DEFLAT_GAUSSIAN_LARGE_REFRESH = 0;
try
    solve_varvisc_schur_sequence(cfg,pbad,'');
    error('test_varvisc_schur_registry:missingRefreshError', ...
          'Invalid refresh interval was accepted.');
catch ME
    assert(strcmp(ME.identifier,'solve_varvisc_schur_sequence:badDeflatRefresh'), ...
           'Unexpected error for invalid refresh interval: %s',ME.message);
end
assert(max(A.vel_recovery_err) < 1e-10,'Schur recovery drifted from K\b.');
fprintf('test_varvisc_schur_registry: ALL ASSERTIONS PASSED\n');
