function assert_varvisc_schur_helpers()
%ASSERT_VARVISC_SCHUR_HELPERS  Reject missing or shadowed local helpers.

    thisDir = fileparts(mfilename('fullpath'));
    localNames = { ...
        'varvisc_schur_assemble_blocks', 'varvisc_schur_assemble_kkt', ...
        'varvisc_schur_context_init', ...
        'varvisc_schur_step_operator', 'varvisc_schur_make_cfg', ...
        'make_varvisc_schur_params', 'add_varvisc_schur_paths'};

    for i = 1:numel(localNames)
        resolved = which(localNames{i});
        if isempty(resolved) || ~strncmp(resolved, thisDir, numel(thisDir))
            error('assert_varvisc_schur_helpers:shadowed', ...
                  'Expected %s under %s, resolved to %s.', ...
                  localNames{i}, thisDir, resolved);
        end
    end

    sharedNames = {'small_eigenvalue_lift', ...
                   'fully_reorthogonalized_lanczos_smallest', ...
                   'gaussian_subspace_basis'};
    expectedSharedDir = fullfile(fileparts(thisDir), ...
        'linear_solves', 'schur_complement', 'local');
    for i = 1:numel(sharedNames)
        resolved = which(sharedNames{i});
        if isempty(resolved) || ...
                ~strncmp(resolved, expectedSharedDir, numel(expectedSharedDir))
            error('assert_varvisc_schur_helpers:shadowedShared', ...
                  'Expected %s under %s, resolved to %s.', ...
                  sharedNames{i}, expectedSharedDir, resolved);
        end
    end

    resolved = which('varvisc_define_case_list');
    if isempty(resolved)
        error('assert_varvisc_schur_helpers:noCaseList', ...
              'varvisc_define_case_list is unavailable; run add_varvisc_schur_paths.');
    end
end
