function opts = varvisc_schur_fig_defaults()
%VARVISC_SCHUR_FIG_DEFAULTS  Figure defaults for the reduced benchmark.
    opts = struct('fontsize',10,'labelfontsize',11,'titlefontsize',12, ...
        'legendfontsize',9,'resolution',200,'single_width',6.5, ...
        'single_height',3.6,'multi_width',7.5,'multi_height',5.0, ...
        'panel_width',3.9,'max_width',14,'marker_targets',8,'close',true);
end
