function write_varvisc_schur_speedup(results_root, all_stats)
%WRITE_VARVISC_SCHUR_SPEEDUP  Iteration comparisons against frozen chol(S_1).
    rows = {};
    for ci = 1:numel(all_stats)
        A = all_stats{ci}; base = A.solver_its.chol;
        for i = 1:numel(A.solver_keys)
            key = A.solver_keys{i}; if strcmp(key,'chol'), continue; end
            v = A.solver_its.(key);
            rows{end+1} = struct('geometry',string(A.geometry), ... %#ok<AGROW>
                'case_name',string(A.case_name),'variant',string(key), ...
                'max_diff_vs_chol',max(base-v), ...
                'max_factor_vs_chol',max(base./max(v,1)), ...
                'median_chol',median(base),'median_variant',median(v));
        end
    end
    writetable(struct2table([rows{:}]),fullfile(results_root,'speedup_summary.csv'));
    write_two_stage_summary(results_root,all_stats);
end

function write_two_stage_summary(root,all_stats)
    baseKey = 'deflate_sequential_shared_subspace';
    augKey = 'deflate_sequential_shared_subspace_augmented';
    rows = {};
    for ci = 1:numel(all_stats)
        A = all_stats{ci};
        if ~all(ismember({baseKey,augKey},A.solver_keys)), continue; end
        base = A.solver_its.(baseKey); aug = A.solver_its.(augKey);
        baseValid = A.solver_flag.(baseKey)==0 & A.solver_err.(baseKey)<=1e-5 ...
            & A.solver_true_relres.(baseKey)<=1e-8;
        augValid = A.solver_flag.(augKey)==0 & A.solver_err.(augKey)<=1e-5 ...
            & A.solver_true_relres.(augKey)<=1e-8;
        valid = baseValid & augValid;
        d = A.augmentation.(augKey);
        row = struct('case_name',string(A.case_name),'steps',A.nsteps, ...
            'baseline_total',sum(base),'augmented_total',sum(aug), ...
            'iteration_savings_percent',100*(1-sum(aug)/max(sum(base),1)), ...
            'baseline_max',max(base),'augmented_max',max(aug), ...
            'valid_pairs',sum(valid),'valid_savings_percent',NaN, ...
            'baseline_nonzero_flags',sum(A.solver_flag.(baseKey)~=0), ...
            'augmented_nonzero_flags',sum(A.solver_flag.(augKey)~=0), ...
            'baseline_max_residual',max(A.solver_true_relres.(baseKey)), ...
            'augmented_max_residual',max(A.solver_true_relres.(augKey)), ...
            'baseline_max_error',max(A.solver_err.(baseKey)), ...
            'augmented_max_error',max(A.solver_err.(augKey)), ...
            'min_base_rank',min(d.base_rank),'min_aug_rank',min(d.aug_rank), ...
            'augmentation_shortfalls',sum(d.aug_rank<d.requested_m), ...
            'arnoldi_columns',sum(d.arnoldi_columns),'residual_columns',sum(d.residual_columns), ...
            'max_vw_orth',max(d.vw_orth),'max_ww_orth',max(d.ww_orth), ...
            'max_arnoldi_relerr',max(d.arnoldi_relerr));
        if any(valid) && sum(base(valid))>0
            row.valid_savings_percent = 100*(1-sum(aug(valid))/sum(base(valid)));
        end
        rows{end+1}=row; %#ok<AGROW>
    end
    if isempty(rows), return; end
    T=struct2table(vertcat(rows{:}));
    writetable(T,fullfile(root,'two_stage_augmentation_summary.csv'));
    fid=fopen(fullfile(root,'two_stage_augmentation_report.md'),'w'); assert(fid>=0);
    cleanup=onCleanup(@()fclose(fid));
    fprintf(fid,'# Two-stage shared-subspace deflation with fresh augmentation\n\n');
    fprintf(fid,['Both arms share V = orth([V_large,V_small]), the same base refresh schedule, ' ...
        'two tau values, PCG tolerance, and warm start from the previous reference solution. ' ...
        'Fresh W uses projected Arnoldi on the current Schur operator, starting from ' ...
        '(I-VV^T)(b-S*x0). The augmented arm uses Z=[V,W] in both stages. ' ...
        'Stage two is built from the operator transformed by its augmented first stage. ' ...
        'W is discarded after each solve.\n\n']);
    fprintf(fid,'| Case | Baseline total iterations | Augmented total iterations | Iterations saved | Valid pairs |\n');
    fprintf(fid,'|---|---:|---:|---:|---:|\n');
    for j=1:height(T)
        fprintf(fid,'| %s | %d | %d | %.2f%% | %d/%d |\n',char(T.case_name(j)), ...
            T.baseline_total(j),T.augmented_total(j),T.iteration_savings_percent(j), ...
            T.valid_pairs(j),T.steps(j));
    end
    fprintf(fid,['\nAll solves remain in totals. A valid pair has both PCG flags zero, ' ...
        'true Schur relative residuals <=1e-8 and relative solution errors <=1e-5 ' ...
        'against the tighter reference solve. The summary CSV also reports savings on valid pairs only. ' ...
        'These are PCG iteration comparisons; building W and the larger coarse matrices costs extra work. ' ...
        'No elapsed-time speedup is inferred.\n\n']);
    fprintf(fid,'Maximum V/W orthogonality error: %.3g; W orthogonality error: %.3g; Arnoldi recurrence error: %.3g.\n\n', ...
        max(T.max_vw_orth),max(T.max_ww_orth),max(T.max_arnoldi_relerr));
    for j=1:height(T)
        fprintf(fid,'- [%s: iterations versus timestep](%s/two_stage_augmentation_comparison.png)\n', ...
            char(T.case_name(j)),char(T.case_name(j)));
    end
    fprintf(fid,'\nData: [paired summary](two_stage_augmentation_summary.csv), [all solver results](all_results.csv).\n');
end
